final avatars = [
  "assets/images/avatars/ava12.png",
  "assets/images/avatars/av13.png",
  "assets/images/avatars/av14.png",
  "assets/images/avatars/av15.png",
  "assets/images/avatars/av16.png",
  "assets/images/avatars/av17.png",
  "assets/images/avatars/av18.png",
  "assets/images/avatars/av19.png",
  "assets/images/avatars/av20.png",
  "assets/images/avatars/av21.png",
  "assets/images/avatars/av22.png",
  "assets/images/avatars/av23.png",
  "assets/images/avatars/av1.jpg",
  "assets/images/avatars/av2.png",
  "assets/images/avatars/av3.jpg",
  "assets/images/avatars/av4.jpg",
  "assets/images/avatars/av5.jpg",
  "assets/images/avatars/av6.jpg",
  "assets/images/avatars/av7.jpg",
  "assets/images/avatars/av8.jpg",
];

final objectsD = [
  "assets/images/3d objects/Ball-2.png",
  "assets/images/3d objects/Cones.png",
  "assets/images/3d objects/Cube-2.png",
  "assets/images/3d objects/Polyhedron.png",
  "assets/images/bubble3.png",
  "assets/images/bubble4.png",
  "assets/images/bubble6.png",
  "assets/images/bg.png",
];
